Repository nezavisimost/liberty-win, pull requests merged in 2022-08, with the labels that each got.

#4 fixing bug issues
  src/LibertyApp/App.xaml.cs
  src/LibertyApp/ConnectionSetup.cs
  src/LibertyApp/LibertyApp.csproj
  src/LibertyApp/Properties/Resource.Designer.cs
  src/LibertyApp/Properties/Resource.resx
  src/LibertyApp/Resources/fuckrkn1.pbk
  src/LibertyApp/ViewModels/ConnectionViewModel.cs
  src/LibertyApp/ViewModels/GlobalViewModel.cs
  src/LibertyApp/ViewModels/MainWindowViewModel.cs
  src/LibertyApp/Views/MainWindow.xaml
  src/LibertyApp/app.manifest
  src/LibertyAppSetup/LibertyAppSetup.vdproj
Labels: bug

#5 Realitime visualizing of connection speed
  src/LibertyApp/Models/ConnectionSpeed.cs
  src/LibertyApp/ViewModels/ConnectionViewModel.cs
  src/LibertyApp/Views/ConnectionView.xaml
Labels: enhancement

#6 Native window, app icon, font
  liberty-win.sln
  src/LibertyApp/App.xaml.cs
  src/LibertyApp/ConnectionSetup.cs
  src/LibertyApp/Language/Strings.Designer.cs
  src/LibertyApp/Language/Strings.resx
  src/LibertyApp/Language/Strings.ru-RU.resx
  src/LibertyApp/LibertyApp.csproj
  src/LibertyApp/Resources/background-connected.jpg
  src/LibertyApp/Resources/background-connecting.jpg
  src/LibertyApp/Resources/background.jpg
  src/LibertyApp/Resources/download-bullet.png
  src/LibertyApp/Resources/font/Exo2-Regular.ttf
  src/LibertyApp/Resources/font/Exo2-SemiBold.ttf
  src/LibertyApp/Resources/icon.ico
  src/LibertyApp/Resources/icon2.ico
  src/LibertyApp/Resources/upload-bullet.png
  src/LibertyApp/Themes/AboutButton.xaml
  src/LibertyApp/Themes/ConnectButton.xaml
  src/LibertyApp/Themes/DonateButton.xaml
  src/LibertyApp/Themes/MenuButton.xaml
  src/LibertyApp/ViewModels/ConnectionViewModel.cs
  src/LibertyApp/ViewModels/MainWindowViewModel.cs
  src/LibertyApp/Views/AboutView.xaml
  src/LibertyApp/Views/ConnectionView.xaml
  src/LibertyApp/Views/DonateView.xaml
  src/LibertyApp/Views/MainWindow.xaml
  src/LibertyApp/Views/MainWindow.xaml.cs
  src/LibertyApp/app.manifest
  src/LibertyAppSetup/LibertyAppSetup.vdproj
Labels: enhancement

#8 Minimize app into system tray
  src/LibertyApp/App.xaml.cs
  src/LibertyApp/Language/Strings.Designer.cs
  src/LibertyApp/Language/Strings.resx
  src/LibertyApp/Language/Strings.ru-RU.resx
  src/LibertyApp/LibertyApp.csproj
  src/LibertyApp/ViewModels/MainWindowViewModel.cs
  src/LibertyApp/Views/ConnectionView.xaml
  src/LibertyApp/Views/MainWindow.xaml
  src/LibertyApp/Views/MainWindow.xaml.cs
  src/LibertyAppSetup/LibertyAppSetup.vdproj
Labels: enhancement

#11 Fixed toggle button
  liberty-win.sln
  src/LibertyApp/Controls/OnlyBindingToggleButton.cs
  src/LibertyApp/Themes/ConnectButton.xaml
  src/LibertyApp/Views/ConnectionView.xaml
Labels: bug

#13 Native window menu with options & Fix Set-VpnConnectionIPsecConfiguration command arguments
  src/LibertyApp/App.config
  src/LibertyApp/App.xaml
  src/LibertyApp/App.xaml.cs
  src/LibertyApp/ConnectionSetup.cs
  src/LibertyApp/Language/Strings.Designer.cs
  src/LibertyApp/Language/Strings.resx
  src/LibertyApp/Language/Strings.ru-RU.resx
  src/LibertyApp/LibertyApp.csproj
  src/LibertyApp/Models/ConnectionSpeed.cs
  src/LibertyApp/Properties/Resources.Designer.cs
  src/LibertyApp/Properties/Resources.resx
  src/LibertyApp/Properties/Settings.Designer.cs
  src/LibertyApp/Properties/Settings.settings
  src/LibertyApp/Themes/MenuButton.xaml
  src/LibertyApp/ViewModels/AboutViewModel.cs
  src/LibertyApp/ViewModels/ConnectionViewModel.cs
  src/LibertyApp/ViewModels/DonateViewModel.cs
  src/LibertyApp/ViewModels/MainWindowViewModel.cs
  src/LibertyApp/Views/AboutView.xaml
  src/LibertyApp/Views/ConnectionView.xaml
  src/LibertyApp/Views/DonateView.xaml
  src/LibertyApp/Views/MainWindow.xaml
  src/LibertyApp/app.manifest
  src/LibertyAppSetup/LibertyAppSetup.vdproj
Labels: bug, enhancement
